services:
  db:
    image: mysql:8.0
    container_name: trafiq_db
    restart: always
    environment:
      MYSQL_DATABASE: trafiq_db
      MYSQL_USER: trafiq_user
      MYSQL_PASSWORD: trafiq_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: trafiq_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DB_HOST=db
      - DB_NAME=trafiq_db
      - DB_USER=trafiq_user
      - DB_PASSWORD=trafiq_password
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: trafiq_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  mysql_data: