# Generated by Django 6.1 on 2026-09-02 13:17

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id_company", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("website", models.URLField(blank=True, max_length=255, null=True)),
                ("sector", models.CharField(blank=True, max_length=100, null=True)),
                ("employee_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "COMPANY",
            },
        ),
        migrations.CreateModel(
            name="ModelVersion",
            fields=[
                ("id_model", models.AutoField(primary_key=True, serialize=False)),
                ("version_code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "MODEL_VERSION",
            },
        ),
        migrations.CreateModel(
            name="SourceProfile",
            fields=[
                ("id_profile", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("target_sectors", models.TextField(blank=True, null=True)),
                ("min_employees", models.IntegerField(default=0)),
                ("max_employees", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "SOURCE_PROFILE",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("sdr", "SDR / Commercial"),
                            ("admin", "Administrateur"),
                        ],
                        default="sdr",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "USER",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                ("id_activity", models.AutoField(primary_key=True, serialize=False)),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="id_user",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        db_column="id_company",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="sourcing.company",
                    ),
                ),
            ],
            options={
                "db_table": "ACTIVITY",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id_contact", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("position", models.CharField(blank=True, max_length=150, null=True)),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                (
                    "linkedin_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "company",
                    models.ForeignKey(
                        db_column="id_company",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="sourcing.company",
                    ),
                ),
            ],
            options={
                "db_table": "CONTACT",
            },
        ),
        migrations.CreateModel(
            name="Signal",
            fields=[
                ("id_signal", models.AutoField(primary_key=True, serialize=False)),
                ("signal_type", models.CharField(max_length=100)),
                ("value", models.TextField(blank=True, null=True)),
                ("source", models.CharField(blank=True, max_length=100, null=True)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        db_column="id_company",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signals",
                        to="sourcing.company",
                    ),
                ),
            ],
            options={
                "db_table": "SIGNAL",
            },
        ),
        migrations.CreateModel(
            name="ProspectScore",
            fields=[
                ("id_score", models.AutoField(primary_key=True, serialize=False)),
                ("fit_score", models.FloatField(default=0.0)),
                ("need_score", models.FloatField(default=0.0)),
                ("intent_score", models.FloatField(default=0.0)),
                ("opportunity_score", models.FloatField(default=0.0)),
                ("final_score", models.FloatField(default=0.0)),
                ("confidence", models.FloatField(default=0.0)),
                ("explanation", models.TextField(blank=True, null=True)),
                (
                    "model_version",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        db_column="id_company",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="sourcing.company",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        db_column="id_model",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="sourcing.modelversion",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        db_column="id_profile",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="sourcing.sourceprofile",
                    ),
                ),
            ],
            options={
                "db_table": "PROSPECT_SCORE",
            },
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                ("id_campaign", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("status", models.CharField(default="draft", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        db_column="id_profile",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to="sourcing.sourceprofile",
                    ),
                ),
            ],
            options={
                "db_table": "CAMPAIGN",
            },
        ),
    ]
