# Generated by Django 6.1 on 2026-09-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceprofile',
            name='fit_weight',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='sourceprofile',
            name='intent_weight',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='sourceprofile',
            name='need_weight',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='sourceprofile',
            name='region',
            field=models.CharField(blank=True, default='Île-de-France', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sourceprofile',
            name='max_employees',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='sourceprofile',
            name='min_employees',
            field=models.IntegerField(default=10),
        ),
    ]
