# Generated by Django 6.1 on 2026-09-28 11:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing', '0002_sourceprofile_fit_weight_sourceprofile_intent_weight_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Activité', 'verbose_name_plural': 'Activités'},
        ),
        migrations.AlterModelOptions(
            name='campaign',
            options={'verbose_name': 'Campagne', 'verbose_name_plural': 'Campagnes'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Entreprise', 'verbose_name_plural': 'Entreprises'},
        ),
        migrations.AlterModelOptions(
            name='modelversion',
            options={'verbose_name': 'Version de modèle', 'verbose_name_plural': 'Versions de modèles'},
        ),
        migrations.AlterModelOptions(
            name='prospectscore',
            options={'verbose_name': 'Score de prospect', 'verbose_name_plural': 'Scores de prospects'},
        ),
        migrations.AlterModelOptions(
            name='signal',
            options={'verbose_name': 'Signal', 'verbose_name_plural': 'Signaux'},
        ),
        migrations.AlterModelOptions(
            name='sourceprofile',
            options={'verbose_name': 'Profil source', 'verbose_name_plural': 'Profils sources'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AlterUniqueTogether(
            name='prospectscore',
            unique_together={('company', 'profile', 'model')},
        ),
        migrations.AddField(
            model_name='prospectscore',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='prospectscore',
            name='model_version',
        ),
    ]
