# Generated by Django 6.1 on 2026-09-28 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing', '0003_alter_activity_options_alter_campaign_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prospectscore',
            old_name='model',
            new_name='model_version',
        ),
        migrations.AlterUniqueTogether(
            name='prospectscore',
            unique_together={('company', 'profile', 'model_version')},
        ),
    ]
